services:
  
  turn-off:
    image: curlimages/curl:8.20.0
    container_name: turn-off
    pull_policy: always
    restart: no
    environment:
      PORTAINER_API_KEY: ${PORTAINER_API_KEY}
      PORTAINER_HOST: ${PORTAINER_HOST}
      ENDPOINT_ID: ${ENDPOINT_ID}
      CONTAINER_ID: ${CONTAINER_ID}
    command:
      - curl
      - -L
      - -H
      - "X-API-Key: ${PORTAINER_API_KEY}"
      - -X
      - POST
      - "http://${PORTAINER_HOST}/api/endpoints/${ENDPOINT_ID}/docker/containers/${CONTAINER_ID}/start"
      - -v
