services:

  oci:
    image: ghcr.io/oracle/oci-cli:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./scripts/turn-on-machine.sh:/usr/local/bin/turn-on-machine
      - ./scripts/turn-off-machine.sh:/usr/local/bin/turn-off-machine
    environment:
      VM_cluster_node_heavy_0: ${VM_cluster_node_heavy_0}
    entrypoint: sleep infinity
  
volumes:
  oci_scripts:
