services:

  oci:
    image: ghcr.io/oracle/oci-cli:latest
    pull_policy: always
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./scripts/turn-off-machine.sh:/usr/local/bin/turn-off-machine
      - ./scripts/turn-on-machine.sh:/usr/local/bin/turn-on-machine
    environment:
      VM_node_heavy_0: ${VM_node_heavy_0}
    entrypoint: null
    command:
      - sh
      - -c
      - |
        chmod +x /usr/local/bin/*
        sleep infinity
  