services:

  turn-on-cluster-heavy-node-0:
    image: ghcr.io/oracle/oci-cli:latest
    container_name: turn-on-cluster-heavy-node-0
    pull_policy: always
    restart: no
    environment:
      MACHINE_OCID: ${MACHINE_OCID}
    entrypoint:
      - oci
      - compute
      - instance
      - action
      - --instance-id
      - $MACHINE_OCID
      - --action
      - START
      - --auth
      - instance_principal
  
  turn-off-cluster-heavy-node-0:
    image: ghcr.io/oracle/oci-cli:latest
    container_name: turn-off-cluster-heavy-node-0
    pull_policy: always
    restart: no
    environment:
      MACHINE_OCID: ${MACHINE_OCID}
    entrypoint:
      - oci
      - compute
      - instance
      - action
      - --instance-id
      - $MACHINE_OCID
      - --action
      - SOFTSTOP
      - --auth
      - instance_principal
